name: Build Project

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest  # Sử dụng máy ảo Windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.1

    - name: Restore NuGet packages
      run: nuget restore BorderlessGaming.sln # Thay bằng tên tệp .sln của bạn

    - name: Build Solution
      run: msbuild BorderlessGaming.sln /p:Configuration=Release /p:Platform="Any CPU"

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Compiled-App
        path: |
          **/bin/Release/*.exe
          **/bin/Release/*.dll
